services:
  nctlivestops:
    image: nctlivestops
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8917:8917
    env_file:
      - flask/.env
    environment:
      - FLASK_ENV=production
    volumes:
      - ./flask:/app/flask:rw

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: