services:
  nctlivestops:
    image: kylenctx/nctlivestops
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8917:8917
    env_file:
      - flask/.env
    environment:
      - FLASK_ENV=production
    deploy:
      resources:
        limits:
          memory: 512M
    volumes:
      - ./flask:/app/flask:rw

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    deploy:
      resources:
        limits:
          memory: 256M

volumes:
  mongodb_data: