services:
  nctlivestops:
    image: kylenctx/nctlivestops
    shm_size: 0.5g
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8917:8917
    env_file:
      - flask/.env
    environment:
      - FLASK_ENV=production
      - DOCKER_ENV=true
    extra_hosts:
      - "nctx.co.uk:104.18.30.191"
      - "www.nctx.co.uk:104.18.30.191"
    deploy:
      resources:
        limits:
          memory: 512M
    volumes:
      - ./flask:/app:rw
      - ./flask/json_files:/app/json_files:ro

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    deploy:
      resources:
        limits:
          memory: 256M

volumes:
  mongodb_data: